name: Publish Images

on:
  push:
    branches:
      - 'main'

jobs:
  plantuml-cli:

    env:
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository }}/plantuml-cli

    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to github registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          tags: |
            type=ref,event=tag
            type=raw,value=0.0.0-{{sha}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:plantuml-cli"
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
